linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    shadow: true
  gofmt:
    simplify: true

linters:
  disable-all: true
  enable:
    - staticcheck
    - unused
    - bodyclose
    - errorlint
    - goconst
    - godot
    - goimports
    - misspell
    - govet
    - deadcode
    - varcheck
    - ineffassign
    - structcheck
    - unconvert
    - errcheck
    - govet
    - gofmt
    - golint
    - gocritic
  fast: false
